#!/bin/sh
#
# @name Gazebo x500 depth mono
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_depth_mono}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# SITL / ROS2 offboard without QGroundControl: 4001 sets NAV_DLL_ACT=2 which blocks arming without a GCS.
param set-default NAV_DLL_ACT 0
